### ISSUE TITLE
Version 1.4.0 has not been deployed

### ISSUE THREAD

**Issue by bengelhardt** [sbt/findbugs4sbt#12]
Version 1.4.0 is referenced in the README but it does not exist in the SBT community repository.

**Comment by BrandonArp** [comment]
+1

**Comment by kmtong** [comment]
+1

**Comment by erosas** [comment]
+1

**Comment by butenkor** [comment]
+1

**Comment by butenkor** [comment]
@jmhofer Any ideas when you could do release ```sbt release```?

**Comment by lukaszbudnik** [comment]
+1

**Comment by ollyhayden** [comment]
+1

**Comment by CodeTripper** [comment]
+1

**Comment by jmhofer** [comment]
Tagged and published, should be available now. Sorry for the delay.
